### ISSUE TITLE
Доработать компонент Button

### ISSUE THREAD

**Issue by ithubspb** [ithubspb/ui-longread#12]
Макет (кнопка для теста): 
https://www.figma.com/file/9lEGLkdaSQ5us2ieQxM8qK/%D0%94%D0%B8%D0%B7%D0%B0%D0%B9%D0%BD-%D0%BC%D0%B0%D0%BA%D0%B5%D1%82?node-id=36%3A196&mode=dev

Внести изменения в стили компонента `Button`, чтобы кнопка соответствовала макету

**Comment by Aniwylle** [comment]
т.т

**Comment by DaniilHub1** [comment]
<3

**Comment by Valdemar697489** [comment]
!

**Comment by Aniwylle** [comment]
(＾◡＾)っ(‿ 人‿)
