### ISSUE TITLE
Разработать компонент Radio

### ISSUE THREAD

**Issue by ithubspb** [ithubspb/ui-longread#13]
Макет (радиокнопка в тесте c пояснением):
https://www.figma.com/file/9lEGLkdaSQ5us2ieQxM8qK/%D0%94%D0%B8%D0%B7%D0%B0%D0%B9%D0%BD-%D0%BC%D0%B0%D0%BA%D0%B5%D1%82?node-id=36%3A202&mode=dev

Свойства:
- text
- onChange

Состояния:
- стили для базового и отмеченного состояний

**Comment by mozglaya** [comment]
.
