### ISSUE TITLE
Разработать компонент "кнопка"

### ISSUE THREAD

**Issue by ithubspb** [ithubspb/ui-longread#3]
Ссылка на макет:
-

Требования к компоненту:
- реализовать возможность настройки текста кнопки, типа кнопки и действия при клике

**Comment by mozglaya** [comment]
.

**Comment by DaniilHub1** [comment]
YAHOOO

**Comment by Daimos2** [comment]
я

**Comment by wleskone** [comment]
негры

**Comment by Valdemar697489** [comment]
Димас нет ,я !

**Comment by YanKarpov** [comment]
Кнопка какой формы? А я так могу работать.

**Comment by Aniwylle** [comment]
> негры

асуждаю
