### ISSUE TITLE
реализовать палитру фирменных цветов

### ISSUE THREAD

**Issue by ithubspb** [ithubspb/ui-longread#5]
# Создать компонент `Layout`

Макет: https://miro.com/app/board/uXjVNLRoqko=/

Его задача - принимать на вход дочерние элементы (children) и отрисовывать их внутри себя

```css
.Layout {
  --color-white: #ffffff;
}
```

```javascript
export function Layout({children}) {
    return <div className="Layout">{children}</div>
}
```

Для проверки стилей импортировать его в `sandbox` и забросить внутрь него один или несколько уже созданных компонентов.

**Comment by mozglaya** [comment]
.
